### ISSUE TITLE
Tokenizer refactoring strategy

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#72]
Implementation Branch: [tokenizer-v1.0.0](https://github.com/meilisearch/tokenizer/tree/tokenizer-v1.0.0)
Draft PR: #77 

## Summary

As a fast search engine, Meilisearch needs a tokenizer that is a pragmatic balance between processing time and relevancy.
The current implementation of the tokenizer leaks clarity and contains ugly hotfixes making contributions, optimizations, and maintenance difficult.

## How to find a pragmatic balance between processing time and relevancy?

First of all, we are not linguists and we don't speak or understand most of the Language that we would want to support, this means that we can't write a tokenizer from scratch and prove that this tokenizer is **relevant** or not.
That's why the current implementation, and the future ones, rely on segmentation libraries like [jieba](https://github.com/messense/jieba-rs), [unicode-segmentation](https://github.com/unicode-rs/unicode-segmentation), or [lindera](https://github.com/lindera-morphology/lindera) to segment texts in words, theses libraries are recommended and included by external contributors in the library.
But this has some limits and the main one is the **processing time**, some libraries, even if they have good relevancy, don't suit our needs because the processing time is too long (👋 Jieba).

### Relevancy

Because we can't measure relevancy by ourselves, we want to continue to rely on the community and external libraries.
In this perspective, we need to make the inclusion of an external library by an external contributor the easiest as possible:

#### Code shape
- [x] Refactor Pipeline by removing preprocessors and making normalizers global #76 
- [x] Refactor `Analyzer` in order to make a new `Tokenizer`registration straightforward #76 
- [x] Simplify the return value of `Tokenizer` (returning a `Script` and a `&str` instead of a `Token`) #76 
- [x] Wrap normalizer in an iterator allowing them to yield several items from 1 (`["l'aventure"]` -> `["l", "'", "adventure"]`) #76 
- [x] ~Add a search mode in `Segmenter` returning all the word derivation~ (tokenizers search mode are doing ngrams internally) 
- [x] Enhance clarity by renaming some structure, function, and files (`Segmenter` instead of `Tokenizer`, `chinese_cmn.rs` instead of `jieba.rs`) #76 
- [x] Create test macro allowing contributors to easily test their tokenizer and improve the trust we have in tests assuring that all tokenizers are equally tested

#### Documentation and contribution processes
- [x] Add documenting comments in main structures (Token, Tokenizer trait..) #76 
- [x] Add a template of a tokenizer as a dummy example of how to add a new tokenizer #76 
- [x] Add a template of a normalizer as a dummy example of how to add a new normalizer 
- [x] Add a CONTRIBUTING.md explaining how to test, bench, and implement tokenizers
- [x] Enhance README.md
- [ ] ~Create an issue triage process differencing each tokenizer scopes (detector, segmenter, normalizer, classifier)~ #88

#### Minimal requirement to have no regressions
- [x] Use `unicode-segmentation` instead of legacy tokenizer for Latin tokenization #76 
- [x] Reimplement Chinese Segmenter (using Jieba)
- [ ] ~Reimplement Japanese Segmenter (using Lindera)~ #89
- [x] Reimplement Deunicode Normalizer only on Script::Latin
- [x] Reimplement traditional Chinese translation preprocessor into a Normalizer only on Language::Cmn
- [x] Reimplement control Character remover Normalizer

### Processing time

Because tokenization has an impact on Meilisearch performances, we have to measure the processing time of every new implementation and define limits that can't be reached in order to be merged. Sometimes, we should think of implementing by ourselves instead of relying on an external library that could significantly impact Meilisearch performances.
- [x] Refactor benchmarks to ease benchmarks creation by any contributor
- [x] Defines hard limits, like throughput thresholds, to objectively accept or refuse a contribution
- [ ] ~Add workflows that run benchmarks on the main branch~ #91

## Publish meilisearch tokenizer as a crates
In order to increase the visibility and external contributions, we may publish this library as a crate.
- [x] #51
- [x] Add a user documentation
- [x] #35

crates link: https://crates.io/crates/charabia

## NLP

For now, we don't plan to use NLP to tokenize in Meilisearch.
