### ISSUE TITLE
Reimplement Japanese Segmenter

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#89]
Reimplement Japanese segmenter using [Lindera](https://github.com/lindera-morphology/lindera).

## TODO list

- [ ] Read Contributing.md about Segmenters implementation
-  Lindera loads dictionaries at initialization
    - [ ] Ensure that Lindera is not initialized at each tokenization
    - [ ] Add a feature flag for Japanese
- [ ] use a custom config to initailize Lindera (better segmentation for search usage)
>  `TokenizerConfig { mode: Mode::Decompose(Penalty::default()), ..TokenizerConfig::default() }`
- [ ] test segmenter
> `関西国際空港限定トートバッグ すもももももももものうち` should give `["関西", "国際", "空港", "限定", "トートバッグ", " ", "すもも", "も", "もも", "も", "もも", "の", "うち"]` 

- [x] Add benchmarks

**Comment by curquiza** [comment]
🔥 🔥
